.Dd May 2024
.Dt BLOCKS 1
.Os
.Sh NAME
.Nm blocks
- emits pf.conf(5) tables from common blocklists
.Sh SYNOPSIS
.Nm blocks get
.Nm blocks emit
.Sh DESCRIPTION
.Nm blocks
is a command line utility that can download common
IP blocklists, and from those blocklists emit
pf.conf(5) tables that can be used when crafting firewall
rules in
.Pa /etc/pf.conf .
.Pp
.Sh EXAMPLES


.Nm blocks get
.br
.br
Downloads blocklists
.Pp
.Nm blocks emit
.br
Emits
pf.conf(5) tables
.Pp
.Sh AUTHORS
The
.Nm blocks
utility and this manual page were written
by 0x1eef <0x1eef@protonmail.com>.
